// ── Channel Constants ──────────────────────────────────────────

export const IPC_CHANNELS = {
  PING: 'ipc:ping',
  GET_APP_VERSION: 'ipc:get-app-version',
  WINDOW_MINIMIZE: 'ipc:window-minimize',
  WINDOW_MAXIMIZE: 'ipc:window-maximize',
  WINDOW_CLOSE: 'ipc:window-close',
  OPEN_FOLDER_DIALOG: 'ipc:open-folder-dialog',
  GET_PROJECTS: 'ipc:get-projects',
  ADD_PROJECT: 'ipc:add-project',
  CREATE_PROJECT_FOLDER: 'ipc:create-project-folder',
  REMOVE_PROJECT: 'ipc:remove-project',
  GET_GLOBAL_THEME: 'ipc:get-global-theme',
  SET_GLOBAL_THEME: 'ipc:set-global-theme',
  SET_PROJECT_THEME: 'ipc:set-project-theme',
  TERMINAL_CREATE: 'ipc:terminal-create',
  TERMINAL_WRITE: 'ipc:terminal-write',
  TERMINAL_RESIZE: 'ipc:terminal-resize',
  TERMINAL_KILL: 'ipc:terminal-kill',
  TERMINAL_KILL_ALL: 'ipc:terminal-kill-all',
  TERMINAL_GET_BUFFER: 'ipc:terminal-get-buffer',
  TERMINAL_GET_LAYOUT: 'ipc:terminal-get-layout',
  TERMINAL_SET_LAYOUT: 'ipc:terminal-set-layout',
  GIT_BRANCH: 'ipc:git-branch',
  NATIVE_NOTIFY: 'ipc:native-notify',
  OPEN_EXTERNAL_URL: 'ipc:open-external-url',
  GET_PRESETS: 'ipc:get-presets',
  SET_PRESETS: 'ipc:set-presets',
  SET_PROJECT_STATUS: 'ipc:set-project-status',
  BROWSER_NAVIGATE: 'ipc:browser-navigate',
  SET_PROJECT_BROWSER: 'ipc:set-project-browser',
  // ── Kanban / Ralph Loop ──────────────────────────────────
  TICKET_GET_ALL: 'ipc:ticket-get-all',
  TICKET_CREATE: 'ipc:ticket-create',
  TICKET_UPDATE: 'ipc:ticket-update',
  TICKET_DELETE: 'ipc:ticket-delete',
  TICKET_TRANSITION: 'ipc:ticket-transition',
  TICKET_REORDER: 'ipc:ticket-reorder',
  PRD_GENERATE: 'ipc:prd-generate',
  PRD_APPROVE: 'ipc:prd-approve',
  PRD_REJECT: 'ipc:prd-reject',
  RALPH_EXECUTE: 'ipc:ralph-execute',
  RALPH_STATUS: 'ipc:ralph-status',
  RALPH_STOP: 'ipc:ralph-stop',
  RALPH_CHOOSE_WORKTREE_DIR: 'ipc:ralph-choose-worktree-dir',
  TICKET_OPEN_AS_PROJECT: 'ipc:ticket-open-as-project',
  // ── Settings ───────────────────────────────────────────────
  GET_OPENAI_KEY: 'ipc:get-openai-key',
  SET_OPENAI_KEY: 'ipc:set-openai-key',
  GET_CLAUDE_KEY: 'ipc:get-claude-key',
  SET_CLAUDE_KEY: 'ipc:set-claude-key',
  // ── File Operations ──────────────────────────────────────────
  FILE_CREATE: 'ipc:file-create',
  FILE_READ: 'ipc:file-read',
  FILE_WRITE: 'ipc:file-write',
  FILE_LIST: 'ipc:file-list',
  // ── App Builder / Expo ────────────────────────────────────
  EXPO_GET_ALL: 'ipc:expo-get-all',
  EXPO_CREATE: 'ipc:expo-create',
  EXPO_ADD: 'ipc:expo-add',
  EXPO_REMOVE: 'ipc:expo-remove',
  EXPO_START: 'ipc:expo-start',
  EXPO_STOP: 'ipc:expo-stop',
  EXPO_STATUS: 'ipc:expo-status',
  EXPO_OPEN_FOLDER_DIALOG: 'ipc:expo-open-folder-dialog',
  EXPO_CHOOSE_PARENT_DIR: 'ipc:expo-choose-parent-dir',
  EXPO_OPEN_AS_PROJECT: 'ipc:expo-open-as-project',
  // ── App Builder Enhancement ─────────────────────────────
  EXPO_TEMPLATE_STATUS: 'ipc:expo-template-status',
  EXPO_REFRESH_TEMPLATES: 'ipc:expo-refresh-templates',
  EXPO_ENSURE_TEMPLATES: 'ipc:expo-ensure-templates',
  EXPO_GENERATE_PRD: 'ipc:expo-generate-prd',
  EXPO_API_KEY_STATUS: 'ipc:expo-api-key-status',
  EXPO_SAVE_PRD: 'ipc:expo-save-prd',
  EXPO_COPY_PRD_IMAGES: 'ipc:expo-copy-prd-images',
  // ── Word Vomit ────────────────────────────────────────────
  WORD_VOMIT_GENERATE_PRD: 'ipc:word-vomit-generate-prd',
  // ── Idea Log ──────────────────────────────────────────────
  IDEA_GET_ALL: 'ipc:idea-get-all',
  IDEA_CREATE: 'ipc:idea-create',
  IDEA_UPDATE: 'ipc:idea-update',
  IDEA_DELETE: 'ipc:idea-delete',
  IDEA_DELETE_BY_PROJECT: 'ipc:idea-delete-by-project',
  // ── Port Service ────────────────────────────────────────────
  PORT_CHECK: 'ipc:port-check',
  PORT_FIND_AVAILABLE: 'ipc:port-find-available',
  PORT_REGISTER: 'ipc:port-register',
  PORT_UNREGISTER: 'ipc:port-unregister',
  PORT_GET_OWNER: 'ipc:port-get-owner',
} as const

export type IPCChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]

/** Frozen set of all allowed channels — used for allowlist checks */
export const ALLOWED_CHANNELS: ReadonlySet<string> = new Set<string>(Object.values(IPC_CHANNELS))
