// Barrel re-export — all consumers continue importing from '@shared/types'
export * from './types/core'
export * from './types/project'
export * from './types/terminal'
export * from './types/browser'
export * from './types/kanban'
export * from './types/fileOps'
export * from './types/appBuilder'
export * from './types/idea'
export * from './types/port'
